FROM confluentinc/cp-kafka:7.6.0
EXPOSE 9092
ENV KAFKA_BROKER_ID=1
ENV	KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
ENV	KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1